version: '3.8'

services:
  app:
    build: .
    image: "springboot-film-rental"
    ports:
      - "8080:8080"
    networks:
      - film_rental-network

networks:
  film_rental-network:
    driver: bridge